namespace PaketLoadScripts

#load "Aardvark.Application.fsx" 
#load "Aardvark.Application.OpenVR.fsx" 
#load "Aardvark.Application.Slim.fsx" 
#load "Aardvark.Application.Slim.GL.fsx" 
#load "Aardvark.Base.Essentials.fsx" 
#load "Aardvark.Base.Incremental.fsx" 
#load "Aardvark.Base.Rendering.fsx" 
#load "Aardvark.Base.Runtime.fsx" 
#load "Aardvark.Rendering.GL.fsx" 
#load "Aardvark.SceneGraph.fsx" 
#load "FShade.Core.fsx" 
#load "FShade.GLSL.fsx" 
#load "Unofficial.OpenTK.fsx" 
#load "Unofficial.OpenVR.fsx" 
#r "../../../packages/Aardvark.Application.OpenVR.GL/lib/netstandard2.0/Aardvark.Application.OpenVR.GL.dll" 