namespace PaketLoadScripts

#load "Aardvark.Application.fsx" 
#load "Aardvark.Base.fsx" 
#load "Aardvark.Base.FSharp.fsx" 
#load "Aardvark.Base.Incremental.fsx" 
#load "Aardvark.Base.Rendering.fsx" 
#load "Aardvark.Compiler.DomainTypes.fsx" 
#load "Aardvark.GPGPU.fsx" 
#load "Aardvark.Rendering.GL.fsx" 
#load "Aardvark.Rendering.Vulkan.fsx" 
#load "Aardvark.SceneGraph.fsx" 
#load "Aardvark.Service.fsx" 
#load "FsPickler.fsx" 
#load "FsPickler.Json.fsx" 
#load "Suave.fsx" 
#r "../../../packages/Aardvark.UI/lib/netstandard2.0/Aardvark.UI.dll" 